/* SPDX-FileCopyrightText: (C) 2026 Gavin John
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Additional permission under GNU GPL version 3 section 7:
 * see LICENSE.EXCEPTION in the root of this project.
 *
 * GENERATED by x86/Development/gen_ntdll.py -- do not edit.
 *
 * Which ntdll routine resolve_all put in which slot.  __ntdll(n)
 * returns the address in slot n; see x86/libc-core.M1 for how the
 * C above calls it, and why the arguments go in backwards.
 */

#ifndef __NTDLL_SLOTS_H
#define __NTDLL_SLOTS_H

#define NT_CREATE      0   /* NtCreateFile: open a file, or make one */
#define NT_READ        1   /* NtReadFile: read */
#define NT_WRITE       2   /* NtWriteFile: write */
#define NT_CLOSE       3   /* NtClose: close, and any other handle */
#define NT_EXIT        4   /* NtTerminateProcess: _exit */
#define NT_RTLPATH     5   /* RtlDosPathNameToNtPathName_U: a DOS path becomes an NT path */
#define NT_SETINFO     6   /* NtSetInformationFile: lseek, and unlink */
#define NT_QUERYINFO   7   /* NtQueryInformationFile: lseek, and fstat */
#define NT_QUERYATTR   8   /* NtQueryAttributesFile: access */
#define NT_QUERYFULL   9   /* NtQueryFullAttributesFile: stat */
#define NT_SETCWD      10  /* RtlSetCurrentDirectory_U: chdir */
#define NT_GETCWD      11  /* RtlGetCurrentDirectory_U: getcwd */
#define NT_DUP         12  /* NtDuplicateObject: dup and dup2 */
#define NT_TIME        13  /* NtQuerySystemTime: time, gettimeofday, clock_gettime */
#define NT_QUERYVOL    14  /* NtQueryVolumeInformationFile: isatty */
#define NT_WAIT        15  /* NtWaitForSingleObject: waitpid */
#define NT_QUERYPROC   16  /* NtQueryInformationProcess: waitpid, for the exit status */
#define NT_DELETE      17  /* NtDeleteFile: unlink and rmdir */
#define NT_VERSION     18  /* RtlGetVersion: uname */
#define NT_MAKEPARAMS  19  /* RtlCreateProcessParameters: __spawn, for the child's parameter block */
#define NT_CREATEPROC  20  /* RtlCreateUserProcess: __spawn */
#define NT_RESUME      21  /* NtResumeThread: __spawn: a new process starts suspended */
#define NT_ALLOC       22  /* NtAllocateVirtualMemory: a real brk, for a program too big to live inside the image */

#endif
